import { 
	Combine, 
	Scissors, 
	RotateCw, 
	Stamp, 
	FileImage, 
	Image as ImageIcon, 
	ArrowDownCircle,
	Shrink, 
	Maximize,
	Crop, 
	RefreshCw, 
	QrCode,
	Eraser,
	Zap,
	Hash, 
	CaseSensitive, 
	StickyNote, 
	FileJson, 
	Lock, 
	Link, 
	Fingerprint,
	Columns2,
	Palette,
	FileCode,
	ScanText,
	Database,
	FileText,
	LayoutGrid,
	Braces,
	Barcode
} from 'lucide-react';

export const ALL_TOOLS = [
	// PDF
	{ id: 'organize', title: 'Organize PDF', description: 'Reorder or delete PDF pages.', href: '/pdf/organize', category: 'pdf', icon: LayoutGrid },
	{ id: 'merge', title: 'Merge PDF', description: 'Combine multiple PDF files into one.', href: '/pdf/merge', category: 'pdf', icon: Combine },
	{ id: 'split', title: 'Split PDF', description: 'Extract pages from your PDF.', href: '/pdf/split', category: 'pdf', icon: Scissors },
	{ id: 'rotate', title: 'Rotate PDF', description: 'Rotate PDF pages permanently.', href: '/pdf/rotate', category: 'pdf', icon: RotateCw },
	{ id: 'watermark', title: 'Watermark PDF', description: 'Add text watermark to PDF.', href: '/pdf/watermark', category: 'pdf', icon: Stamp },
	{ id: 'word-to-pdf', title: 'Word to PDF', description: 'Convert Word to PDF document.', href: '/pdf/word-to-pdf', category: 'pdf', icon: FileText, isExternal: true },
	{ id: 'excel-to-pdf', title: 'Excel to PDF', description: 'Convert Excel to PDF document.', href: '/pdf/excel-to-pdf', category: 'pdf', icon: FileText, isExternal: true },
	{ id: 'pdf-to-excel', title: 'PDF to Excel', description: 'Convert PDF to editable Excel spreadsheet.', href: '/pdf/pdf-to-excel', category: 'pdf', icon: Database, isExternal: true },
	{ id: 'jpg-to-pdf', title: 'JPG to PDF', description: 'Convert images to PDF.', href: '/pdf/jpg-to-pdf', category: 'pdf', icon: FileImage },
	{ id: 'pdf-to-jpg', title: 'PDF to JPG', description: 'Extract pages as JPG images.', href: '/pdf/pdf-to-jpg', category: 'pdf', icon: ImageIcon },
	{ id: 'pdf-to-word', title: 'PDF to Word', description: 'Convert PDF to Word document.', href: '/pdf/pdf-to-word', category: 'pdf', icon: FileCode, isExternal: true },
	{ id: 'pdf-compressor', title: 'Compress PDF', description: 'Reduce PDF file size.', href: '/pdf/compress', category: 'pdf', icon: ArrowDownCircle },
	
	// Image
	{ id: 'compressor', title: 'Image Compressor', description: 'Reduce image file size.', href: '/image/compressor', category: 'image', icon: Shrink },
	{ id: 'background-remover', title: 'Background Remover', description: 'Remove backgrounds using AI.', href: '/image/background-remover', category: 'image', icon: Eraser },
	{ id: 'vectorizer', title: 'SVG Vectorizer', description: 'Convert images to clean SVG.', href: '/image/vectorizer', category: 'image', icon: Zap },
	{ id: 'resizer', title: 'Image Resizer', description: 'Change image dimensions.', href: '/image/resizer', category: 'image', icon: Maximize },
	{ id: 'cropper', title: 'Image Cropper', description: 'Crop and rotate images.', href: '/image/crop', category: 'image', icon: Crop },
	{ id: 'converter', title: 'Format Converter', description: 'Convert JPG, PNG, WebP.', href: '/image/converter', category: 'image', icon: RefreshCw },
	{ id: 'svg-to-png', title: 'SVG to PNG', description: 'Convert SVG to PNG image.', href: '/image/svg-to-png', category: 'image', icon: ImageIcon },
	{ id: 'qr-generator', title: 'QR Generator', description: 'Create custom QR codes.', href: '/image/qr-generator', category: 'image', icon: QrCode },
	{ id: 'barcode-generator', title: 'Barcode Generator', description: 'Create various barcode types.', href: '/image/barcode-generator', category: 'image', icon: Barcode },
	{ id: 'ocr', title: 'Image to Text', description: 'Extract text from images.', href: '/image/ocr', category: 'image', icon: ScanText },
	
	// Text
	{ id: 'word-counter', title: 'Word Counter', description: 'Count words and characters.', href: '/text/word-counter', category: 'text', icon: Hash },
	{ id: 'case-converter', title: 'Case Converter', description: 'Change text casing.', href: '/text/case-converter', category: 'text', icon: CaseSensitive },
	{ id: 'lorem-ipsum', title: 'Lorem Ipsum', description: 'Generate placeholder text.', href: '/text/lorem-ipsum', category: 'text', icon: StickyNote },
	{ id: 'markdown', title: 'Markdown Editor', description: 'Real-time markdown editing.', href: '/text/markdown', category: 'text', icon: FileCode },
	
	// Dev
	{ id: 'json-formatter', title: 'JSON Formatter', description: 'Format and minify JSON.', href: '/dev/json-formatter', category: 'dev', icon: FileJson },
	{ id: 'code-formatter', title: 'Code Formatter', description: 'Beautify HTML, CSS, JS code.', href: '/dev/code-formatter', category: 'dev', icon: Braces },
	{ id: 'base64', title: 'Base64 Tool', description: 'Encode/decode Base64.', href: '/dev/base64', category: 'dev', icon: Lock },
	{ id: 'password-generator', title: 'Password Generator', description: 'Secure random passwords.', href: '/dev/password-generator', category: 'dev', icon: Lock },
	{ id: 'url-tool', title: 'URL Tool', description: 'Encode/decode URLs.', href: '/dev/url-tool', category: 'dev', icon: Link },
	{ id: 'uuid-generator', title: 'UUID Generator', description: 'Generate UUID v4.', href: '/dev/uuid-generator', category: 'dev', icon: Fingerprint },
	{ id: 'diff-checker', title: 'Diff Checker', description: 'Compare two texts.', href: '/dev/diff-checker', category: 'dev', icon: Columns2 },
	{ id: 'color-picker', title: 'Color Picker', description: 'Pick and convert colors.', href: '/dev/color-picker', category: 'dev', icon: Palette },
];
